CREATE TABLE T_ADMIN_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255),
    LOGIN_NAME VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PRIMARY KEY (ID)
)

INSERT INTO T_ADMIN_USER (EMAIL, LOGIN_NAME, NAME, PASSWORD) VALUES ('PQ@126.COM', 'PQ', 'PQ', 'E10ADC3949BA59ABBE56E057F20F883E');